### ISSUE TITLE
Primary Navigation- Spacing at 990px

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#20]
Primary navigation is tight at the 990px breakpoint. 
Can we introduce the menu button at the 990px breakpoint rather than at 768px?
![image](https://cloud.githubusercontent.com/assets/9142185/13474183/d8b2fce8-e08a-11e5-869b-457f06144e60.png)

**Comment by adam-s-p-** [comment]
This hasn't been resolved yet.
To be clear, can we have the Primary Nav at <991px look like this:
![image](https://cloud.githubusercontent.com/assets/9142185/13614873/9630d4ca-e540-11e5-93ca-584708cc0004.png)
with "About" "Practices" "Team" "News" and "Quick Consult" hidden inside of the menu button?

**Comment by mike3run** [comment]
Oh okay, I understood by menu button and the screen shot that you wanted the quick consult button gone on that size no problem I got that

**Comment by adam-s-p-** [comment]
Ok thanks!
