### ISSUE TITLE
Please do not use IDs in CSS 

### ISSUE THREAD

**Issue by kylamedina** [itsMakeable/mbfirm.com---MARKUP#21]
This goes against BEM syntax.

https://www.smashingmagazine.com/2014/07/bem-methodology-for-small-projects/#one-class-to-rule-them-all

**Comment by mike3run** [comment]
The IDs are used for layout purposes and on items that get repeated a class is used instead (ie. headers) like SMACSS a valid BEM methodology says :)

http://getbem.com/introduction/

![captura de pantalla 2016-03-02 a las 2 38 39 p m](https://cloud.githubusercontent.com/assets/7088511/13474759/1731f236-e085-11e5-9f10-d1e2411c71ef.png)


https://smacss.com/book/type-layout

![captura de pantalla 2016-03-02 a las 2 39 06 p m](https://cloud.githubusercontent.com/assets/7088511/13474764/1bebb37a-e085-11e5-8e09-9471fd079e9e.png)


https://www.youtube.com/watch?v=6co781JgoqQ
