### ISSUE TITLE
Arrow Button Consistency 

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#25]
Arrow is much larger in the Learn More CTA in the Header of the Homepage than in the Quote Container of the Homepage. 
![image](https://cloud.githubusercontent.com/assets/9142185/13474843/dc77f9e8-e08d-11e5-83f7-52747d363a42.png)

![image](https://cloud.githubusercontent.com/assets/9142185/13474832/ce1811ee-e08d-11e5-8b84-c1035f128f95.png)

And the arrow is pushed far to the right in the Practices section of the Homepage.
![image](https://cloud.githubusercontent.com/assets/9142185/13475069/d6e843a6-e08e-11e5-80a2-5826742387eb.png)

#### All Buttons should have the same CSS. 

Example: the two buttons above should be the same button but the button arrow CSS is unnecessarily nested in both images.
##### Hero Arrow:
```
#hero .right-arrow
  position: absolute;
  max-width: 25px;
  top: 25%;
  right: 10%;
```
##### Pull Quote Arrow:
```
#pull-quotes .quotes .quote .right-arrow
  position: absolute;
  max-width: 20px;
  top: 25%;
  right: 15%;
```

**Comment by adam-s-p-** [comment]
Arrows are still not consistent.
The button in the quote container is larger than all the others. The should all be that same size.

**Comment by mike3run** [comment]
All are using the same CSS now
