### ISSUE TITLE
Button Hover States

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#27]
All outlined buttons should hover by filling with the color of the stroke.
For example, a learn more button with a white stroke should fill white on hover.

This holds true for all buttons sitewide, including pagination arrows, like those in the news section of the Homepage.

![image](https://cloud.githubusercontent.com/assets/9142185/13475215/a3296832-e08f-11e5-921e-817af969a6b5.png)

![image](https://cloud.githubusercontent.com/assets/9142185/13475206/9b626ec8-e08f-11e5-89cf-817155365bea.png)

**Comment by mike3run** [comment]
And the inside text would be in what color?

Please provide sketch with button states for reference

**Comment by adam-s-p-** [comment]
In red-stroked buttons– text would be white
In white-stroked buttons– text would be dark blue

**Comment by mike3run** [comment]
Done for the learn more buttons

Could I get some svgs  where only FILL or OUTLINE are used in case of the pagination buttons since I need that to be consistent to get the effect going :)

So this one is currently on hold but done 50%

**Comment by adam-s-p-** [comment]
Sorry, I just saw this. Can you please be more specific with what you want?

**Comment by adam-s-p-** [comment]
@kylamedina refer to issue #48 regarding the Submit button in the Quick Consult field.
