### ISSUE TITLE
Slider Pagination

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#28]
On sliders, like on the Homepage Header and the News section of the Homepage, Selected pagination dots should be larger than deselected pagination dots, as per the comps.

![image](https://cloud.githubusercontent.com/assets/9142185/13475489/385ddf4a-e091-11e5-95a3-432899b9af2d.png)

![image](https://cloud.githubusercontent.com/assets/9142185/13475493/3fcf0df8-e091-11e5-9b41-f4b58a2246e7.png)

**Comment by mike3run** [comment]
The carousel plugin doesn't allow good vertical alignment if the active one is larger that the rest.

**Comment by adam-s-p-** [comment]
The way you are doing it is fine. Thanks.

**Comment by mike3run** [comment]
they are both in the middle i don't understand this last issue

**Comment by adam-s-p-** [comment]
![image](https://cloud.githubusercontent.com/assets/9142185/13710586/4dc46dba-e788-11e5-95dc-1e562ab57858.png)
