### ISSUE TITLE
Related Articles cannot be in rows.

### ISSUE THREAD

**Issue by kylamedina** [itsMakeable/mbfirm.com---MARKUP#29]
Putting related articles in rows are creating the following issue at around 1280px. Please review a possible solution I provided below.

<img width="867" alt="related-articles" src="https://cloud.githubusercontent.com/assets/1031900/13474876/fdb8ce5c-e08d-11e5-9108-a9a993ac076d.png">

The stylus plugin [Jeet](http://jeet.gs) has a solution by using 'cycle'

> column(ratios = 1, offset = 0, cycle = 0, uncycle = 0, gutter = jet.gutter) : Want to make a gallery but don't want to specify a row every 4 pictures? column(1/4, cycle: 4) - done. Want to change it up when you get down to mobile? Maybe just show 2 images per row? uncycle your 4-item cycle then... column(1/2, uncycle: 4, cycle: 2) - done. Need to adjust column gutters for a specific container? col(1/4, gutter: .5)

**Comment by mike3run** [comment]
The plugin option crashes using multiple breakpoints ie:

```
col(1/2, cycle: 2)
+above(2)
  col(1/3, cycle: 3)
```

everything goes insane, so I opted for flexbox just in this case

**Comment by mike3run** [comment]
Mobile views on sketch would be appreciated for this one.

**Comment by adam-s-p-** [comment]
@mike3run see issue #51

**Comment by kylamedina** [comment]
@ 768px the boxes break to two across, at @ 540px, it breaks to one across.

**Comment by mike3run** [comment]
thanks I got the new sketch! i'm working on all remaining issues today, expect a PR in a couple hours
