### ISSUE TITLE
Layout- Contact Information

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#32]
![image](https://cloud.githubusercontent.com/assets/9142185/13477406/31e320a4-e09a-11e5-8d64-07d2406ada3c.png)
Needs to move right, should always be able to be eclipsed by quote container.

**Comment by mike3run** [comment]
Please elaborate on that one. I didn't get the point 

Thanks

**Comment by adam-s-p-** [comment]
The contact information hangs about 20px to the left of the quote container. The left-most edge contact information should align to the left-most edge of the quote container.

**Comment by mike3run** [comment]
Please check [issue 33](https://github.com/itsMakeable/mbfirm.com/issues/33) I think that could help more on a global scale :)
