### ISSUE TITLE
Container Needs Design Measures

### ISSUE THREAD

**Issue by mike3run** [itsMakeable/mbfirm.com---MARKUP#33]
Could we get some container measures on each responsive state maybe like

1 : 90%
2:  80%
...
5 : 960px 

Or something like that, maybe that could help with some of the alignment issues :)

**Comment by mike3run** [comment]
I'm thinking like the measures you gave on the headers but on a global scale for the global container of things

**Comment by toddhlynch** [comment]
The containers are not fluid on most sections of the site.  They should jump at the defined breakpoints to the grids that we outlined in the component document.

The only section which is full bleed is the header image.

Items like the footer, which have a full bleed background color, should still have their content inside a fixed width container.

**Comment by mike3run** [comment]
That's okay I still would need the measures though :)

**Comment by mike3run** [comment]
![captura de pantalla 2016-03-02 a las 6 05 55 p m](https://cloud.githubusercontent.com/assets/7088511/13480127/6da6b842-e0a1-11e5-9f70-6bfc6d2093c0.png)

Something like that would greatly help since as of now I haven't touched the styling on the container element it's not even mobile first that part currently.

**Comment by adam-s-p-** [comment]
Does the file linked in #51 help with this?
