### ISSUE TITLE
Body Copy- Subheaders

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#34]
Can we increase the line height of subheaders from 1.2 to 1.4?

![image](https://cloud.githubusercontent.com/assets/9142185/13478288/50fc0b0a-e09e-11e5-9c40-d1137db94e86.png)

**Comment by adam-s-p-** [comment]
Hi, I am still waiting for this :)

**Comment by mike3run** [comment]
This change did happen maybe we are not on the same page regarding what do you mean by subheaders or by line-height.

I did change the line height to 1.4 to the "Our Philosophy" tag and alikes

**Comment by adam-s-p-** [comment]
I apologize for not being specific.
This was in reference to H3, the copy that says "At Martzell and Bickford..."

Thanks again.

**Comment by adam-s-p-** [comment]
Perfect. Thanks.
