### ISSUE TITLE
Container Width- Body Copy on News Page

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#38]
Can we have the body copy container on the news page match that of the team member page in browsers <540px.
Currently is too wide.
Example:
![image](https://cloud.githubusercontent.com/assets/9142185/13480347/3740c9fa-e0ab-11e5-8e38-78c761eb9387.png)

Should look like this on all pages:
![image](https://cloud.githubusercontent.com/assets/9142185/13480360/4c459b82-e0ab-11e5-9816-a54300d7997e.png)

**Comment by mike3run** [comment]
I think it would be best if first we dealt with the general containers issue that way everything else container-related would be solved 

[View Issue 33](https://github.com/itsMakeable/mbfirm.com/issues/33)

**Comment by adam-s-p-** [comment]
@mike3run see file link in issue #51
