### ISSUE TITLE
News Page- Photo Caption

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#39]
Photo caption on the news page cuts into colored background above in browsers <540px. The colored background should come down halfway behind the photo.
![image](https://cloud.githubusercontent.com/assets/9142185/13480405/a27874a2-e0ab-11e5-8837-4d831021c96e.png)

**Comment by mike3run** [comment]
Please provide mobile views for that page or section. I just made what I got.

**Comment by adam-s-p-** [comment]
@mike3run Please see file linked in issue #51 for reference.
