### ISSUE TITLE
H2 Scale Down Proportionally

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#40]
Can we have H2 text scale down proportionally, like H1 does.
For example:
80% at 990px
60% at <540px

![image](https://cloud.githubusercontent.com/assets/9142185/13480517/532d7b44-e0ac-11e5-97bd-12d884dd1877.png)

**Comment by mike3run** [comment]
H1 had the sketch files to compare against.

Maybe get a cheat sheet on responsive typography to be applied a global scale?

That could help :)

**Comment by adam-s-p-** [comment]
@mike3run Look at file linked in issue #51 for reference.

**Comment by adam-s-p-** [comment]
Great. Now can we increase line height to 1.4?

![image](https://cloud.githubusercontent.com/assets/9142185/13792123/b795de72-eac6-11e5-9972-7ebabea330d5.png)

**Comment by adam-s-p-** [comment]
To be clear, only after it's scaled down after 990px
