### ISSUE TITLE
Team Members- Thumbnails

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#41]
At maximum width, thumbnails in the More Team Members section of the Team Members page should be 350x350px as per the comp.

Also, please center the type and align it vertically beneath the thumbnails.

Currently looks like this:
![image](https://cloud.githubusercontent.com/assets/9142185/13481716/0329c5ee-e0b6-11e5-8bd4-b958e9f51bc9.png)

Should look like this:
![image](https://cloud.githubusercontent.com/assets/9142185/13481725/152e5318-e0b6-11e5-845d-3e03fc1593b9.png)

**Comment by mike3run** [comment]
No problem for max sizes, but also wold be good to get comps on the rest of the views as well. Thanks

**Comment by adam-s-p-** [comment]
Should work the same way as the carousel on the home page does.
The thumbnails still expand beyond 350x350 and the type is not centered.
Please fix.
Thank you.

**Comment by mike3run** [comment]
But on the homepage they are not laid out evenly? Should I just go with the homepage design then?

**Comment by mike3run** [comment]
Done, now its the same as on the homepage :)
