### ISSUE TITLE
Global Layout- Columns and Container

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#44]
The content container should have widths as defined below:

XLARGE
>= 1525px
Container Width: 1465px
Column Width: 95px
Gutter Width: 27px

LARGE
>= 1200px
Container Width: 1167px
Column Width: ~81px
Gutter Width: 15px

MEDIUM
>= 992px
Container Width: 940px
Column Width: 62px
Gutter Width: 15px

SMALL
>= 768px
Container Width: 720px
Column Width: ~50px
Gutter Width: 8px

For example, this page should have the columns as shown in this image.  Any browser width wider than this would stay at this width.  It is not fluid, the columns jump to the breakpoints.

Also, as shown in this image, there is a one column gutter, then the left column is 3 cols, then a 1 col gutter, then the main content is 6cols, then there is a one column gutter.

![image](https://cloud.githubusercontent.com/assets/9142185/13502236/11b54016-e138-11e5-86ce-6337ef5816de.png)

**Comment by mike3run** [comment]
This can work! I'll put those container max-width values.

For the gutters and the column per-se the [jeet.js](http://jeet.gs/) you assigned the project to be built with doesn't work with fixed units either for the columns or the gutters, it uses percentages and ratios.

But let's see how having fixed max-widths affects the layout I'm thinking it will help a lot
