### ISSUE TITLE
Quick Consult- Expandable Field

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#46]
The field titled "Brief Description..." in the Quick Consult form currently has a tab that allows you to expand it all the way right and down.

This should not be available.

![image](https://cloud.githubusercontent.com/assets/9142185/13614081/c7d0464a-e53c-11e5-96f2-6a3150858541.png)

**Comment by mike3run** [comment]
It is considered good for UX to let users expand a `textarea` since they will be writing more stuff than a single line.

But it's your call I'll disable it then :)

**Comment by adam-s-p-** [comment]
Thank you, Mike.
I think a better idea would be if it expands down after every complete line typed

**Comment by mike3run** [comment]
This is something a bit more custom in the JS department so for ease of mind of everyone i'll just give that area a bit more of room for the area and disable the expansion.

**Comment by adam-s-p-** [comment]
The way the field works when you type is fine for now. You don't need to give it more space, just please remove the tab on the bottom right that allows you to expand the field manually.
Thanks!

**Comment by mike3run** [comment]
I think I got a great middle ground! Now the user can expand it but only down :)

**Comment by adam-s-p-** [comment]
Awesome! 
Now can we just remove the tab on the lower right that allows the user to expand it manually?

**Comment by kylamedina** [comment]
@adam-s-p- can't do that
