### ISSUE TITLE
Team Member- H2 scaling

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#49]
At <991px width, H2 should scale down to 22pt as per the comps.
![image](https://cloud.githubusercontent.com/assets/9142185/13617544/4abd446c-e54d-11e5-9cd7-a4133e38b0be.png)

Applies to Issue #40

**Comment by kylamedina** [comment]
@adam-s-p- lets talk

**Comment by adam-s-p-** [comment]
@kylamedina whenever you need to
