### ISSUE TITLE
Team Member Page- Fixed Center Type Container

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#56]
Page content seems to be fixed left.
![image](https://cloud.githubusercontent.com/assets/9142185/13788693/3641b6ca-eab7-11e5-8af3-e56b1aaea972.png)

**Comment by mike3run** [comment]
I just used the column sizes and offsets you provided

**Comment by adam-s-p-** [comment]
Should be one column separation between between copy on  left and body copy at browser widths 1525px and 1200px as per components document.

![image](https://cloud.githubusercontent.com/assets/9142185/13789504/cb48f1b8-eaba-11e5-92d2-d4aeb8d4b7cd.png)
