### ISSUE TITLE
Icon Navigation- Practice Titles on Two Lines

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#7]
Make all Practice titles two lines in browsers larger than 768px, for example:
![image](https://cloud.githubusercontent.com/assets/9142185/13470321/9fafe246-e079-11e5-8b00-048ee30c3f57.png)

Currently, line breaks are inconsistent among practices:
![image](https://cloud.githubusercontent.com/assets/9142185/13470349/c49a2904-e079-11e5-9caa-80117dae7e4f.png)

**Comment by mike3run** [comment]
Again I believe this can be solved by getting the container measures on different sizes :) 

Since the only thing I'm doing here is using the plugins you provided to make 7 even columns across the container.

With a well defined container it should render the same view

**Comment by mike3run** [comment]
I'm trying a fixed idea using the measures of the sketch to set the max width of each icon option but it becomes un-fluid and on certain breakpoints it breaks into a new line.

So I'll wait for the container measures and keep dealing with new issues :)

**Comment by adam-s-p-** [comment]
I tested by adding line breaks and it works out fine.

Please add <br> codes as follows:
"Mesothelioma & <br> Asbestos"
"Legal <br> Malpractice"
"Oil, Gas & <br> Environmental"
"Criminal <br> Law"
"Class Action <br> Lawsuits"
"Product <br> Liability" 
"Maritime <br> Law"

Thanks!

**Comment by mike3run** [comment]
Perfect! It's done
