### ISSUE TITLE
Homepage- News Section 

### ISSUE THREAD

**Issue by adam-s-p-** [itsMakeable/mbfirm.com---MARKUP#71]
1. at 540px type container should mimic header type container and span 335px.
2. Truncate body copy at 160 characters.

![image](https://cloud.githubusercontent.com/assets/9142185/13820541/278abf74-eb74-11e5-9785-417b71951457.png)

**Comment by mike3run** [comment]
I kind of started that solution but I couldn't figure the rest out.

https://github.com/itsMakeable/mbfirm.com---MARKUP/blob/master/src/coffee/plugins/text-slider.coffee

I left comments there to help with that part.

Basically the idea would be to store all of that content in order on an array and also make another array with the truncated content. then trigger the change depending on the viewport.

^^^ That part I couldn't figure how to translate to code lol
